web:
  image: reload/drupal-apache-ssl
  ports:
    - '80/tcp'
    - '443/tcp'
  volumes:
    - './web:/var/www/html'
    - './drupal.make:/var/www/html/drupal.make'
    - './docker/settings.php:/var/www/html/sites/default/settings.php:ro'
    - './docker/settings.local.php:/var/www/html/sites/default/settings.local.php:ro'
    - './docker/drupal-cron.conf:/etc/cron.d/drupal-cron.conf:ro'
    - './docker/prepare-environment.sh:/etc/my_init.d/prepare-environment.sh'
    - './docker/php.ini:/etc/php/5.6/mods-available/ding.ini'
    - "${SSH_AUTH_SOCK}:/tmp/ssh-agent"
  links:
    - db
    - memcached
  environment:
    PHP_EXTRA_EXTENSIONS: msgpack igbinary memcached
    SSH_AUTH_SOCK: /tmp/ssh-agent
  working_dir: /var/www/html
db:
  image: mariadb
  ports:
    - '3306/tcp'
  environment:
    MYSQL_ROOT_PASSWORD: Iec4aiphies7ohFa5fo5koh3aisaew
    MYSQL_DATABASE: db
    MYSQL_USER: db
    MYSQL_PASSWORD: ichai4IesaeSainohV0oT2ca9hooNi
gulp:
  image: node:argon
  volumes:
    - './web/profiles/ding2/themes/ddbasic:/src'
  entrypoint: "/bin/sh -c 'cd /src && npm install --unsafe-perm && node_modules/.bin/gulp sass'"
memcached:
  image: memcached
varnish:
  image: mobulum/varnish:1.4.0
  environment:
    VCL_FILE: /opt/ding-docker.vcl
    LISTEN_PORT: 80
    # Below an evil hack to pass extra options to `varnishd`. Uses the
    # fact that ${TELNET_PORT} is unquoted in the run.sh script.
    TELNET_PORT: 6083 -p vcc_err_unref=off
  volumes:
    - './docker/ding-docker.vcl:/opt/ding-docker.vcl'
    - './web/profiles/ding2/ding2.vcl:/opt/ding2.vcl'
  ports:
    - '80/tcp'
  links:
    - web
