version: "2"
services:
  # Webroot container shared between the web, php, gulp and drush containers.
  webroot:
    image: tianon/true
    volumes:
      - './web:/var/www/web'
      - './docker/docker.settings.php:/var/www/web/sites/default/settings.php:cached'
  web:
    image: reload/drupal-apache-fpm
    ports:
      - '80'
    volumes_from:
      - webroot
    environment:
      VIRTUAL_HOST: ding2.docker
    # The drupal-apache-fpm image expects the container that runs fpm to be
    # available as "fpm" so we alias our link to the php container.
    links:
      - php:fpm

  php:
    image: reload/drupal-php7-fpm:7.0
    ports:
      - '9000'
    environment:
      PATH: '/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      PHP_SENDMAIL_PATH: /usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"
      PHP_EXTRA_EXTENSIONS: msgpack igbinary memcached
      BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://web/", "selenium2" : { "wd_host" : "http://selenium-hub:4444/wd/hub" } } } }'
    volumes_from:
      - webroot
    volumes:
      - './docker/drupal-cron.conf:/etc/cron.d/drupal-cron.conf:ro'
      - './docker/php.ini:/etc/php/7.0/mods-available/ding.ini'
      - './docker/prepare-environment.sh:/etc/my_init.d/prepare-environment.sh'
    working_dir: /var/www/web
    links:
      - db
      - memcached

  db:
    image: mariadb:10
    ports:
      - '3306'
    # If you want to use a local database dump, remove the volumes_from, place the
    # dump in ./docker/db and add the following
    volumes:
      - './docker/db:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  # Mailcapture with a webinterface.
  mailhog:
      image: mailhog/mailhog
      # Web-inteface exposed on mail.ding2.docker
      environment:
        VIRTUAL_HOST: mail.ding2.docker

  gulp:
    image: node:argon
    volumes_from:
      - webroot
    entrypoint: "/bin/sh -c 'cd /var/www/web/profiles/ding2/themes/ddbasic && npm install && node_modules/.bin/gulp watch'"
    user: root

  memcached:
    image: memcached
    ports:
      - '11211'

  selenium-hub:
    image: selenium/hub:2.44.0
    ports:
      - '4444'
    environment:
      VIRTUAL_HOST: selenium-hub.ding2.docker
      VIRTUAL_PORT: 4444

  selenium-chrome:
    image: selenium/node-chrome:2.44.0
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    volumes:
      # Mount /dev/shm to increase available shared memory - otherwise Chrome
      # will crash.
      # https://github.com/elgalu/docker-selenium/issues/20#issuecomment-325090454
      - '/dev/shm:/dev/shm'

volumes:
  drush-cache:
