version: '3'

services:
  web:
    image: reload/drupal-apache-fpm:latest
    ports:
      - '80'
      - '443'
    depends_on:
      - fpm
    volumes:
      - 'projectroot:/var/www/'
      - '${HOME}/.local/share/mkcert:/mkcert:ro'
      - '${HOME}/.local/share/dev_certificates:/cert:rw'
    environment:
      # Ensure dory redirects from http to https. We want to nag
      # people into doing development on valid HTTPS.
      HTTPS_METHOD: redirect
      # Ensure dory/nginx-proxy goes via port 80.
      VIRTUAL_PORT: '80'
      VIRTUAL_HOST: ding2.docker
      MKCERT_DOMAINS: "ding2.docker mail.ding2.docker"
      DRUSH_OPTIONS_URI: http://ding2.docker

  fpm:
    image: reload/drupal-php7-fpm:7.0
    ports:
      - '9000'
    depends_on:
      - db
      - memcached
    working_dir: /var/www/web
    volumes:
      - 'projectroot:/var/www/'
      - './docker/my_init.d/install-cron.sh:/etc/my_init.d/install-cron.sh'
    environment:
      PATH: '/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      DRUSH_OPTIONS_URI: http://ding2.docker
      PHP_SENDMAIL_PATH: /usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"
      PHP_EXTRA_EXTENSIONS: 'memcache'
      XDEBUG_MODE: "debug,develop"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      discover_client_host: "0"

  db:
    image: ding2/ding2-mysql:master
    ports:
      - '3306/tcp'
    # If you want to use a local database dump, remove the image, place the
    # dump in ./docker/db and add the following
    # volumes:
    #   - './docker/db:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  # Mailcapture with a webinterface.
  mailhog:
    image: mailhog/mailhog
    # Web-inteface exposed on mail.ding2.docker
    environment:
      VIRTUAL_HOST: mail.ding2.docker

  memcached:
    image: memcached
    ports:
      - '11211'

  gulp:
    image: node:argon
    volumes:
      - 'cache:/npm-cache'
      - 'projectroot:/var/www/'
    entrypoint: "/bin/sh -c 'cd /var/www/web/profiles/ding2/themes/ddbasic && npm install --no-optional && node_modules/.bin/gulp watch'"
    user: root

volumes:
  # NPM cache that survives docker-reset.sh
  cache:
  db-data:
  projectroot:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
